server.port=8080
file.channel.path=otp-codes.log
outbox.dir=notifications-outbox
db.url=jdbc:postgresql://localhost:5432/makolov_otp
db.user=postgres
db.password=postgres
jwt.secret=111
jwt.ttl.seconds=3600
